name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  continuous-integration:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Using Node.js
        uses: actions/setup-node@v2 
        with:
          node-version: '22.16' 

      - name: Install dependencies, build and test
        env: 
          DATABASE_URL: ${{ secrets.DATABASE_URL }} 
        run: |
          npm install
          npm run build # O build agora terá acesso à DATABASE_URL
          npm run test